#pragma once

//
// This file contains all IDs of game assets 
//

#define ID_TEX_MARIO 0
#define ID_TEX_ENEMY 10
#define ID_TEX_MISC 20
#define ID_TEX_TILES 30
#define ID_TEX_MISC_V2 40
#define ID_TEX_TILES_v2 50

// LIVE OBJECTS

#define OBJECT_TYPE_BORDER -1
#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_KOOPAS	3
#define OBJECT_TYPE_COIN 4
#define OBJECT_TYPE_PLATFORM 5
#define OBJECT_TYPE_GROUND	6
#define OBJECT_TYPE_BOX_PLATFORM 7
#define OBJECT_TYPE_PIPE 8
#define OBJECT_TYPE_BLOCKS 9
#define OBJECT_TYPE_PRIZE_BLOCK 10
#define OBJECT_TYPE_PARAGOOMBA	11
#define OBJECT_TYPE_PIRANHAPLANT	12

// BACKGROUND OBJECTS

#define OBJECT_TYPE_BACKGROUND_BUSH 101
#define OBJECT_TYPE_BACKGROUND_CLOUD 102
#define OBJECT_TYPE_BACKGROUND_HILL 103

#define OBJECT_TYPE_SUPER_MUSHROOM 20
#define OBJECT_TYPE_SUPER_LEAF 21

// PROJECTILES
#define OBJECT_TYPE_FIREBALL	80

// PORTAL
#define OBJECT_TYPE_PORTAL	50

#pragma region MARIO 

#define ID_SPRITE_MARIO 10000
#define ID_SPRITE_MARIO_BIG (ID_SPRITE_MARIO + 1000)
#define ID_SPRITE_MARIO_BIG_IDLE (ID_SPRITE_MARIO_BIG + 100)
#define ID_SPRITE_MARIO_BIG_IDLE_LEFT (ID_SPRITE_MARIO_BIG_IDLE + 10)
#define ID_SPRITE_MARIO_BIG_IDLE_RIGHT (ID_SPRITE_MARIO_BIG_IDLE + 20)

#define ID_SPRITE_MARIO_BIG_WALKING (ID_SPRITE_MARIO_BIG + 200)
#define ID_SPRITE_MARIO_BIG_WALKING_LEFT (ID_SPRITE_MARIO_BIG_WALKING + 10)
#define ID_SPRITE_MARIO_BIG_WALKING_RIGHT (ID_SPRITE_MARIO_BIG_WALKING + 20)
#define ID_SPRITE_MARIO_BIG_RUNNING (ID_SPRITE_MARIO_BIG + 300)
#define ID_SPRITE_MARIO_BIG_RUNNING_LEFT (ID_SPRITE_MARIO_BIG_RUNNING + 10)
#define ID_SPRITE_MARIO_BIG_RUNNING_RIGHT (ID_SPRITE_MARIO_BIG_RUNNING + 20)
#define ID_SPRITE_MARIO_BIG_JUMP (ID_SPRITE_MARIO_BIG + 400)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK (ID_SPRITE_MARIO_BIG_JUMP + 10)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_LEFT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN (ID_SPRITE_MARIO_BIG_JUMP + 20)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_LEFT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 6)
#define ID_SPRITE_MARIO_BIG_SIT (ID_SPRITE_MARIO_BIG + 500)
#define ID_SPRITE_MARIO_BIG_SIT_LEFT (ID_SPRITE_MARIO_BIG_SIT + 10)
#define ID_SPRITE_MARIO_BIG_SIT_RIGHT (ID_SPRITE_MARIO_BIG_SIT + 20)
#define ID_SPRITE_MARIO_BIG_BRACE (ID_SPRITE_MARIO_BIG + 600)
#define ID_SPRITE_MARIO_BIG_BRACE_LEFT (ID_SPRITE_MARIO_BIG_BRACE + 10)
#define ID_SPRITE_MARIO_BIG_BRACE_RIGHT (ID_SPRITE_MARIO_BIG_BRACE + 20)

#define ID_SPRITE_MARIO_DIE (ID_SPRITE_MARIO + 3000)

#define ID_SPRITE_MARIO_SMALL (ID_SPRITE_MARIO + 2000)
#define ID_SPRITE_MARIO_SMALL_IDLE (ID_SPRITE_MARIO_SMALL + 100)
#define ID_SPRITE_MARIO_SMALL_IDLE_LEFT (ID_SPRITE_MARIO_SMALL_IDLE + 10)
#define ID_SPRITE_MARIO_SMALL_IDLE_RIGHT (ID_SPRITE_MARIO_SMALL_IDLE + 20)

#define ID_SPRITE_MARIO_SMALL_WALKING (ID_SPRITE_MARIO_SMALL + 200)
#define ID_SPRITE_MARIO_SMALL_WALKING_LEFT (ID_SPRITE_MARIO_SMALL_WALKING + 10)
#define ID_SPRITE_MARIO_SMALL_WALKING_RIGHT (ID_SPRITE_MARIO_SMALL_WALKING + 20)
#define ID_SPRITE_MARIO_SMALL_RUNNING (ID_SPRITE_MARIO_SMALL + 300)
#define ID_SPRITE_MARIO_SMALL_RUNNING_LEFT (ID_SPRITE_MARIO_SMALL_RUNNING + 10)
#define ID_SPRITE_MARIO_SMALL_RUNNING_RIGHT (ID_SPRITE_MARIO_SMALL_RUNNING + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP (ID_SPRITE_MARIO_SMALL + 400)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK (ID_SPRITE_MARIO_SMALL_JUMP + 10)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN (ID_SPRITE_MARIO_SMALL_JUMP + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 6)

#define ID_SPRITE_MARIO_SMALL_SIT (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_SIT_LEFT (ID_SPRITE_MARIO_SMALL_SIT + 10)
#define ID_SPRITE_MARIO_SMALL_SIT_RIGHT (ID_SPRITE_MARIO_SMALL_SIT + 20)

#define ID_SPRITE_MARIO_SMALL_BRACE (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_BRACE_LEFT (ID_SPRITE_MARIO_SMALL_BRACE + 10)
#define ID_SPRITE_MARIO_SMALL_BRACE_RIGHT (ID_SPRITE_MARIO_SMALL_BRACE + 20)

#pragma endregion 

//BRICK

#define ID_SPRITE_BRICK 20000

//GOOMBA

#define ID_SPRITE_GOOMBA 30000
#define ID_SPRITE_GOOMBA_WALK (ID_SPRITE_GOOMBA + 1000)
#define ID_SPRITE_GOOMBA_DIE (ID_SPRITE_GOOMBA + 2000)

//COIN

#define ID_SPRITE_COIN 40000

//CLOUD

#define ID_SPRITE_CLOUD 50000
#define ID_SPRITE_CLOUD_BEGIN (ID_SPRITE_CLOUD + 1000)
#define ID_SPRITE_CLOUD_MIDDLE (ID_SPRITE_CLOUD + 2000)
#define ID_SPRITE_CLOUD_END (ID_SPRITE_CLOUD + 3000)

//PIPE 

#define ID_SPRITE_PIPE 80000
#define	ID_SPRITE_PIPE_HEAD_LEFT (ID_SPRITE_PIPE + 1000)
#define	ID_SPRITE_PIPE_HEAD_RIGHT (ID_SPRITE_PIPE + 2000)
#define	ID_SPRITE_PIPE_BODY_LEFT (ID_SPRITE_PIPE + 3000)
#define	ID_SPRITE_PIPE_BODY_RIGHT (ID_SPRITE_PIPE + 4000)

//BACKGROUND BUSH

#define ID_SPRITE_BACKGROUND_BUSH 1010000

//BACKGROUND CLOUD

#define ID_SPRITE_BACKGROUND_CLOUD 1020000
#define ID_SPRITE_BACKGROUND_CLOUD_LEFT_TOP (ID_SPRITE_BACKGROUND_CLOUD + 1001)
#define ID_SPRITE_BACKGROUND_CLOUD_LEFT_BOTTOM (ID_SPRITE_BACKGROUND_CLOUD + 1002)
#define ID_SPRITE_BACKGROUND_CLOUD_MIDDLE_TOP (ID_SPRITE_BACKGROUND_CLOUD + 2001)
#define ID_SPRITE_BACKGROUND_CLOUD_MIDDLE_BOTTOM (ID_SPRITE_BACKGROUND_CLOUD + 2002)
#define ID_SPRITE_BACKGROUND_CLOUD_RIGHT_TOP (ID_SPRITE_BACKGROUND_CLOUD + 3001)
#define ID_SPRITE_BACKGROUND_CLOUD_RIGHT_BOTTOM (ID_SPRITE_BACKGROUND_CLOUD + 3002)

//BACKGROUND HILL

#define ID_SPRITE_BACKGROUND_HILL 1030000
#define ID_SPRITE_BACKGROUND_HILL_LEFT_CLIFF (ID_SPRITE_BACKGROUND_HILL + 1001)
#define ID_SPRITE_BACKGROUND_HILL_RIGHT_CLIFF (ID_SPRITE_BACKGROUND_HILL + 1002)
#define ID_SPRITE_BACKGROUND_HILL_LEFT_EDGE (ID_SPRITE_BACKGROUND_HILL + 2001)
#define ID_SPRITE_BACKGROUND_HILL_RIGHT_EDGE (ID_SPRITE_BACKGROUND_HILL + 2002)
#define ID_SPRITE_BACKGROUND_HILL_BODY (ID_SPRITE_BACKGROUND_HILL + 3000)

//PARAGOOMBA

#define ID_SPRITE_PARAGOOMBA 120000
#define ID_SPRITE_PARAGOOMBA_DIE (ID_SPRITE_PARAGOOMBA + 1000)
#define ID_SPRITE_PARAGOOMBA_FOOT_WALK (ID_SPRITE_PARAGOOMBA + 2000)
#define ID_SPRITE_PARAGOOMBA_WING_WALK (ID_SPRITE_PARAGOOMBA + 3000)
#define ID_SPRITE_PARAGOOMBA_WING_FLY (ID_SPRITE_PARAGOOMBA_WING_WALK + 100)

#define ID_ANI_PARAGOOMBA_DIE 991210
#define ID_ANI_PARAGOOMBA_FOOT_WALK 991220
#define ID_ANI_PARAGOOMBA_WING_WALK 991230
#define ID_ANI_PARAGOOMBA_WING_FLY 991231

//PIRANHAPLANT

#define ID_SPRITE_PIRANHAPLANT 130000

#define ID_SPRITE_PIRANHAPLANT_RED (ID_SPRITE_PIRANHAPLANT + 1000)

#define ID_SPRITE_PIRANHAPLANT_RED_OPEN_DOWN_LEFT (ID_SPRITE_PIRANHAPLANT_RED + 111)
#define ID_SPRITE_PIRANHAPLANT_RED_OPEN_DOWN_RIGHT (ID_SPRITE_PIRANHAPLANT_RED + 112)
#define ID_SPRITE_PIRANHAPLANT_RED_OPEN_UP_LEFT (ID_SPRITE_PIRANHAPLANT_RED + 121)
#define ID_SPRITE_PIRANHAPLANT_RED_OPEN_UP_RIGHT (ID_SPRITE_PIRANHAPLANT_RED + 122)

#define ID_SPRITE_PIRANHAPLANT_RED_CLOSE_DOWN_LEFT (ID_SPRITE_PIRANHAPLANT_RED + 211)
#define ID_SPRITE_PIRANHAPLANT_RED_CLOSE_DOWN_RIGHT (ID_SPRITE_PIRANHAPLANT_RED + 212)
#define ID_SPRITE_PIRANHAPLANT_RED_CLOSE_UP_LEFT (ID_SPRITE_PIRANHAPLANT_RED + 221)
#define ID_SPRITE_PIRANHAPLANT_RED_CLOSE_UP_RIGHT (ID_SPRITE_PIRANHAPLANT_RED + 222)

#define ID_ANI_PIRANHAPLANT_CHOMP 99130000

#define ID_ANI_PIRANHAPLANT_CHOMP_RED (ID_ANI_PIRANHAPLANT_CHOMP + 1000)

#define ID_ANI_PIRANHAPLANT_CHOMP_RED_DOWN_LEFT (ID_ANI_PIRANHAPLANT_CHOMP_RED + 11)
#define ID_ANI_PIRANHAPLANT_CHOMP_RED_DOWN_RIGHT (ID_ANI_PIRANHAPLANT_CHOMP_RED + 12)
#define ID_ANI_PIRANHAPLANT_CHOMP_RED_UP_LEFT (ID_ANI_PIRANHAPLANT_CHOMP_RED + 21)
#define ID_ANI_PIRANHAPLANT_CHOMP_RED_UP_RIGHT (ID_ANI_PIRANHAPLANT_CHOMP_RED + 22)

//FIREBALL

#define ID_SPRITE_FIREBALL 800000

#define ID_ANI_FIREBALL 99800000
